BASE64TST.PGM: BASE64TST.PGM.SQLRPGLE
BASE64TST.PGM: TEXT = Demo of BASE64 SQL Functions
PRINTER.MODULE: PRINTER.RPGLE
PRINTER.MODULE: TEXT = Printer Procedures
RPGPGM1.PGM: RPGPGM1.PGM.SQLRPGLE
RPGPGM1.PGM: TEXT = RPG Program One
